Server=tcp:pinyasova.database.windows.net,1433;
Initial Catalog=Прогр;
Persist Security Info=False;
User ID={your_username};
Password={your_password};
MultipleActiveResultSets=False;
Encrypt=True;
TrustServerCertificate=False;
Connection Timeout=30;
